COVID-19-electronic-health-system/Corona-tracker

README.md

- Added my notes from the Zoom call we had last night at 6:45. Not much to add, just a few additional notes and things that stood out to me, primarily.
- Added some additional notes and styling in order to help guide us to deciding on one critical feature of what we want our IPR to be Monday / early next week. It would be awesome if we could add multiple features by then (it seems like the symptom-tracker and a crowdsourced resource availability mechanism are both popular ideas), but I think we should focus in on at least having one core functionality done and finished before adding additional features/ideas.

Update README: Add Notes from call, streamline thinking

---

client/config-overrides.js
client/package-lock.json
client/package.json
client/src/components/App.js
client/src/components/Login.js
client/src/utils/constants.js
package-lock.json

[Ticket](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/12)
**NOTE: PLEASE TRY THIS BEFORE MERGING. EVERYTHING WORKS FINE ON DESKTOP, BUT WHEN INSPECTING AND GOING TO THE IPHONE X PRESET, FOR EXAMPLE, YOU HAVE TO RE-SIGN IN WITH YOUR BLOCKSTACK ACCOUNT IN ORDER TO ACCESS (REQUIRES THE SECRET PHRASE AND A QUICK PASSWORD RESET (DON'T HAVE TO GO TO EMAIL TO CONFIRM). ONCE YOU'RE LOGGED IN ONCE IN MOBILE, IT WILL REMEMBER AND YOU WON'T HAVE TO RE-SIGN-IN EACH TIME. NOT A BIG DEAL FOR NOW, BUT COULD BE CUMBERSOME LATER. THIS IS A BLOCKSTACK-WIDE ISSUE... MAY BE SOMETHING TO DISCUSS LATER.**
**WHEN TESTING, LET ME KNOW IF YOU WANT THE SECRET PHRASE FOR THE BLOCKSTACK ID CORONATRACKER.ID.BLOCKSTACK I MADE**
As per the README, we decided to utilize Blockstack to create …

Incorporate Blockstack Authentication

---

client/package-lock.json
client/public/manifest.json
client/src/components/App.js
client/src/components/Login.js
client/src/css/App.css
client/src/css/Login.css

Created a responsive UI for the Login page. I'm not a UI guy, so I'm not sure if this is the right way to go about overriding `react-bootstrap` or reformatting the page between mobile and not.
Let me know what you guys think! 
Mobile view
Desktop view

Create responsive UI for login page

---

README.md

Filled out the FAQ questions from Ameer, the systems architect we spoke with on 3/13.

Update README to fill out FAQ

---

client/src/components/WeeklyTracker.js
client/src/components/WeeklyTrackerDay.js
client/src/css/themePalette.css

the color and background properties was duplicated for themePalette.css so I created seperate classes for background , slider , and text

Theme palettehotfix

---

README.md
client/package-lock.json
client/package.json
client/src/components/App.js

[Issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/13)
- Updated `App.js` to get the logged-in user's name as a POC that we've established a connection to Radiks.
- Added setup instruction to the README for individuals to get this setup/run in their own local environments (**let me know if they don't work or there's extra steps needed!!**)
Like I've mentioned before, I haven't worked with Blockstack/Gaia/Radiks before, but I believe I'm following best practices. @tesla809 @chancelorb I believe you both have had some experience with this stuff before, so if you'd be willing to set this up locally and take a look before we merge it in that would be much appreciated!

Setup and Establish Connection with Local Radiks server

---

client/package.json
client/src/components/ChartJs.js
client/src/components/TempChart.js

TempChart.js - chart component built with react-charts library
ChartJs.js - chart component built with chart.js library
I did't add this components to the App.js for this commit in order to avoid unnecessary conflicts.
Before start the server make sure that you run 'npm install' to install chart.js library.

charts components

---

README.md

Added "Questions Related to Stack?" section to README.md. 
Added people who are implementing features as points of contact for new devs.

Update README.md with contact section- "Questions Related to Stack?"

---

Translations.md

I've put in a bit of an example from the frame that I am working on in Italian. I will get more time to work on this later, but if people want to start using this format for the other languages, go right ahead!

Master translation doc from wireframes

---

client/src/components/App.js

I believe this fixes the ability where sometimes signing in would give an error. Blockstack is finicky and a lot of the documentation is a bit out of date.
@BrianHHough hopefully this should fix your [bug](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/71)

HOTFIX: Fix inability to sign in

---

client/package.json

This PR
* adds a standard configuration for prettier by blockstack
* fixes #94

Add prettier config

---

client/package-lock.json
client/src/components/App.js
client/src/components/DiagnosticContainer.js
client/src/css/DiagnosticContainer.css
client/src/css/Temperature.css

Just created a PR for those working on #16 - I'm not sure who's been working on what, but I figured I could create the overlying `DiagnosticContainer.js` while all of you (the people I requested who are assigned to this ticket) can see if this fits into your flow easily. 
I was under the assumption you were all making subcomponents, so hopefully we can merge it in and then your pieces can fit nicely within this.
Let me know what you all think!
This is what the UI now looks like when logged in, I added in `Temperature.js` as an example of how you can all start putting your individual pieces into this.

Created DiagnosticContainer scaffolding to fit interactive UI in it

---

client/src/components/Temperature.js

This PR
* converts the Temperature component class to a functional component
* closes #91 
**Test plan (required)**
* start radiks server
* yarn start
The component is not yet used

use all records for average temperature

---

client/src/components/DiagnosticContainer.js
client/src/components/Temperature.js

This PR
* adds some dummy data to the temperature component

Add data for average temperature

---

CONTRIBUTING.md

Provides instructions for setting up the MongoDB server for Windows. It's fairly simple, but I'm not sure that it's the best best way to do it. (`mongod` -> `mongo`)
Gonna be testing this again on a separate Windows computer tomorrow with a fresh install of the repository, MongoDB, and radiks-server. It works on current installation though.
Potentially closes #108 ? @friedger

Windows setup for MongoDB in CONTRIBUTING.md

---

CONTRIBUTING.md

Reverts COVID-19-electronic-health-system/Corona-tracker#123

Revert "Windows setup for MongoDB in CONTRIBUTING.md"

---

client/package.json

This PR
* removes the duplicate entry `devDependencies` in `package.json`
* fixes #127

Remove duplicate devDependencies

---

client/src/components/DiagnosticContainer.js
client/src/components/Temperature.js
client/src/redux/actions/actions.js
client/src/redux/actions/checkups.js
client/src/redux/actions/observations.js
client/src/redux/reducers/rootReducer.js

This PR
* adds initial data as `Observations`
* adds actions to save and load observations (not used yet)
* uses state data in `Temperature` component
* loads data on first rendering

V2: Temperature from state

---

.gitignore
server/.gitignore

Added .DS_Store to .gitignore files to prevent macOS generate .DS_Store files from appearing in project folders.

Updated/added .gitignore files

---

client/package-lock.json
client/package.json
client/src/components/App.js
client/src/components/ButtonGroup.js
client/src/components/DiagnosticContainer.js
package-lock.json

Refined toggle button group using Material UI this time for symptom screen. Considered all of your feedback. Let me know if I need to make any other changes!

Added improved toggle button

---

client/package-lock.json
client/package.json
client/src/components/DiagnosticContainer.js
client/src/components/NavBar.js

Sorry I am late to the party but what can I say!

Changed the layout of the NavBar and DiagnosticContainer

---

client/package-lock.json
client/src/components/SymptomsTracker.js
client/src/components/survey-view/checkbox-button/CheckboxButton.js

Resolving Issue #166 
- Adding checkbox components into Symptom Tracker component.
- Removing unnecessary, duplicate, or redundant code in related components to allow these to mesh together seamlessly
(seems to need some styling with the new combined components)

Combining SymptomTracker component with CheckboxButton and/or SingleCheckboxButton

---

client/src/components/DiagnosticContainer.js

header added
small horizontal line added

added: Let’s log your health for today: header

---

client/src/components/NavBar.js
client/src/css/App.css
client/yarn.lock

- Added a link to in `NavBar` so that clicking the education tab hits the education endpoints
- Updated styling so that our background fills the screen

Route nav bar to education page

---

client/src/components/NavBar.js
client/src/redux/actions/actions.js
client/src/redux/actions/navigation.js
client/src/redux/reducers/navigation.js
client/src/redux/reducers/rootReducer.js

@friedger Hi, I moved navigation state to redux, let me know what you think.
closes #174

Navigation redux

---

client/src/components/App.js

This PR
* checks manually for pending blockstack signin
* fixes #181 
See blockstack connect issue https://github.com/blockstack/ux/issues/300

Check manually for pending login

---

client/src/components/DiagnosticContainer.js
client/src/components/Disclaimer.js
client/src/css/DiagnosticContainer.css

So far there's only logic for someone clicking agree (a bool switch on state) and nothing happens if you click disagree. Logic for agree/disagree should probably be made a separate issue

Disclaimer popup styling

---

client/src/components/FactQuizContainer.js
client/src/components/NavBar.js

fixed: bug cards blocks navbar

---

client/src/components/DiagnosticContainer.js
client/src/components/HealthLogToggle.js

feature: toggle button between health log and show me more

---

client/src/components/DiagnosticContainer.js
client/src/components/Scroll.js

make scroll

---

client/src/components/App.js
client/src/components/DiagnosticContainer.js
client/src/components/Layout.js

make layout

---

client/src/components/FactQuizContainer.js
client/src/css/FlashCards.css
client/src/css/Login.css

Deleted some undeeded elements from FactQuiz as they are in the layout #217

changed FactQuiz style to go with layout

---

client/src/components/App.js
client/src/components/DiagnosticContainer.js
client/src/components/HealthLogToggle.js
client/src/components/Layout.js
client/src/components/MyHealthLog.js

Issue fixed https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/212

Button symptom tracker

---

client/src/components/Chart.js

FastFix - add correct selection of the store data in the Chart.js component

FastFix - Chart.js

---

client/package-lock.json
client/src/components/survey-view/checkbox-button/SingleCheckboxButton.js

headache restyle

---

client/src/components/SymptomsTracker.js

#252 adjust symptom tracker layout based on size of screen

---

client/package.json
client/src/components/SymptomsTracker.js
client/src/components/survey-view/checkbox-button/CheckboxButton.js
client/src/models/observation.js
client/src/tests/SymptomsTracker.test.js
client/yarn.lock

fixes #237 
- Added capability to save and fetch data from Gaia on survey submit 
- Store data as a new file each time so that we can iterate through all user data.

Store user data in Gaia

---

client/src/components/Chart.js
client/src/tests/Chart.test.js

fixes #285 
1) add correct selection of the data from the store in Chart.js (I thought I submit this fix before)
2) Fixt Chart.test.js
There still console error message:

Chart.js test fix

---

client/src/components/SymptomsTracker.js
client/src/components/survey-view/checkbox-button/SingleCheckboxButton.js

Needed to undo changes in #288

HOTFIX: undo changes to survey

---

client/package.json
client/src/components/SymptomsTracker.js

fixes #290 
- Surveys will now be stored such as observation/000000${observationNumber}.json

Refactor survey naming convention

---

client/src/components/SymptomsTracker.js
client/src/redux/actions/submit-survey.js
client/src/redux/reducers/submit-survey.js

fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/304

HOTFIX: symptom tracker bug

---

client/src/components/SymptomsTracker.js

No Issue associated
Needed to move the `putFile` functionality back in `submitSurvey()` to fix build

HOTFIX: reset putfile location

---

client/src/components/App.js

I added a popup alert in App.js that reminds the user to fill in their health survey for today.

Added Popup Alert to fill in survey in App.js

---

client/src/components/App.jsx
client/src/components/Calendar.jsx
client/src/components/Chart.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/calendar.js
client/src/redux/reducers/calendar.js
client/src/redux/reducers/rootReducer.js
client/src/tests/Chart.test.js
client/src/tests/__snapshots__/Chart.test.js.snap
client/src/tests/__snapshots__/Chart.test.jsx.snap

working on issue: #277
- add action and reducer for Calendar.js component.
When user click on the date, event listener dispatch redux action with the target date. Action ready to send request with selected date to the backend.

PR on issue: #277 - Calendar + Redux

---

client/package.json
client/src/components/App.jsx
client/src/components/Chart.jsx
client/src/components/DiagnosticContainer.jsx
client/yarn.lock

Hotfix, for some reason FullCalendar is not working and is breaking master. I'm going to suggest utilizing a different package, as FullCalendar seems like not the best use case.

HOTFIX: Calendar broke master

---

client/package.json
client/src/components/SymptomsTracker.jsx

fixes #317 
In issue [comments](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/317) @njordhov mentioned that there was a trailing zeroes problem when the number of observations file is over ten.
Test using a profile with under ten surveys submitted
- [Read here for more …

Added fix for saving observations

---

client/src/components/Calendar.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/MyHealthLog.jsx
client/src/components/SymptomsTracker.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/observations.js
client/src/redux/reducers/observations.js
client/src/redux/reducers/rootReducer.js
client/src/tests/redux/reducers/observations.test.js

fixes #331 
- Queries Gaia in `DiagnosticContainer`
- Sets the number of current queries in Redux
- Fixes `SymptomsTracker` to read from Redux store to get number of observations, abstracts away complexity farther down the DOM tree.
- Moved WeeklyTracker, Calendar into appropriate component
TODO write a full suite of `DiagnosticContainer` unit tests

Query Gaia and Cleanup Logic

---

.github/pull_request_template.md
client/src/components/MyHealthLog.jsx

HOTFIX: removed duplicate dependencies

---

client/src/components/MyHealthLog.jsx

hotfix to `MyHealthLog.jsx` to saparate `AppCalendar` and `WeeklyTracker` from `Link` component

hotfix MyHealthLog

---

client/src/components/DiagnosticContainer.jsx
client/src/components/survey-view/checkbox-button/CheckboxButton.jsx
client/src/components/survey-view/checkbox-button/SingleCheckboxButton.jsx

fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/351
The bug was caused by not correctly handling the event in TemperatureAutocomplete subcomponent.

temperature

---

CONTRIBUTING.md
README.md

fixes #324 
This updates the readme technology stack section per @SomeMoosery and overhauls the contributing file.
The contributing file had a lot of duplicate content, placeholders for information, and was difficult to read through. This PR creates a TOC and reorganizes the existing content, removes redundant information, and expands on simple tutorials and procedures for working with the CoronaTracker project.
This will only affect documentation and the links were all tested/verified.
- _Note: I did not but marked this complete as this does not affect the code base, only the documentation_
- _Note: I did not but …

Update readme and contributing file

---

client/package.json
client/src/components/MyHealthLog.jsx
client/src/components/WeeklyTracker.jsx
client/src/components/WeeklyTrackerDay.jsx
client/src/tests/WeeklyTrackerTest.test.jsx
client/src/tests/__snapshots__/WeeklyTrackerTest.test.jsx.snap
client/yarn.lock

fixes #347 fixes #348 
- Updates CSS so that weekly sliders are in a near-final state
- Implements `react-spring` as it's already being used in other places
- Removes `react-toastify` as it doesn't best fit our needs
- Moves logic of receiving and manipulating dates higher up in the DOM (HealthLog)
**Need to add additional mock tests for all edge cases once we near our 4/15 deadline but have all necessary components ready**
- …

Stylize WeeklyTracker to near-final state

---

client/package.json
client/src/components/App.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/Disclaimer.jsx

Fixes #330
After agreeing to the disclaimer, the user will now be redirected to the onboarding screen. This creates a more appropriate flow that encourages the user to input their information as soon as possible.
Previously, the disclaimer modal would only appear on the Log screen if the user had not seen it before, but not necessarily agreed to it. Now, the disclaimer modal appears on any screen after logging in, and will only disappear after the user agrees to it. This will help ensure that the user agrees to the disclaimer before using any part of the app.
To test …

Redirect to onboard screen on disclaimer agree (#330)

---

client/package.json
client/src/components/MyHealthLog.jsx

Take survey button

---

client/package.json
client/src/components/Calendar.jsx
client/src/components/HealthLogToggle.jsx
client/src/components/Table.jsx
client/src/components/WeeklyTracker.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/healthToggle.js
client/src/redux/reducers/healthToggle.js
client/src/redux/reducers/rootReducer.js
client/src/tests/WeeklyTrackerTest.test.jsx

fixes #341 
- Moved state for whether or not we were in "Health Log" or "Show Me More" view to Redux
- Sent "current" observation to Redux (current being all if you're going directly from "Health Log" -> "Show Me More"
- "Show Me More" table now has real-user values
- Swiping on a card for a certain day under calendar only shows the details for that day in "Show Me More" (allows for further customization down the line)
- **AS USUAL, WE WILL NEED TO RETROACTIVELY WRITE TESTS TO ENSURE QUALITY. I'M NOT AN EXPERT AT TDD BUT IT'S SOMETHING TO IMPLEMENT POST-BETA** …

Show Real Data Detail

---

client/package.json
client/src/components/HealthLogToggle.jsx
client/src/components/MyHealthLog.jsx

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes**
fixes #371 

restyle-healthLogToggle

---

client/package.json
client/src/components/LogHealthSlider.jsx
client/src/components/MyHealthLog.jsx
client/src/tests/LogHealthSlider.test.jsx
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap

Fixes #332 
Creates the "Log My Health" slider, styled similarly to the wireframes, that takes the user to the survey page when it is swiped.
**Desktop**
**Desktop with notification settings**
**iPhone X**
**iPhone X with notification settings**

Add "Log My Health" slider (#332)

---

client/package.json
client/src/components/HealthLogToggle.jsx
client/src/components/Login.jsx
client/src/components/More.jsx
client/src/components/MyHealthLog.jsx
client/src/css/buttons.js

Fixes #381 
Makes buttons have more consistent styling throughout app.
**Newly styled "Get Started" button**

Make button styling more consistent (#381)

---

client/package.json
client/src/components/Chart.jsx

fixes #387 
- Updates styling for charts
- Passes in user data for dates, temperatures
- **Using this map, we could pretty easily pass in a different background color (for example) if the user's temperature was over a specific amount in the future if we want**
- Not much new to add here, can add E2E tests post-beta

Uses real chart data and fixes styling

---

client/package.json
client/src/components/Calendar.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/WeeklyTracker.jsx
client/src/components/WeeklyTrackerDay.jsx
client/src/css/Calendar.css
client/src/redux/actions/actions.js
client/src/redux/actions/observations.js
client/src/redux/reducers/observations.js
client/src/tests/redux/reducers/observations.test.js

Fixes #336 
- Add dots above calendar dates to indicate the user has completed a survey on that date
-  Fetch and store observation data in Redux store when `DiagnosticContainer` loads
**Calendar with survey completed dots/indicators**

Add survey completed date indicator to calendar (#336)

---

client/package.json
client/src/components/Layout.jsx

Fixes #389 
Scroll bar no longer appears on education screen unless necessary.
**Education screen with no scroll bar**

Only show vertical scroll bar when necessary (#389)

---

client/package.json
client/src/components/LogHealthSlider.jsx
client/src/components/WeeklyTracker.jsx
client/src/components/WeeklyTrackerDay.jsx
client/src/css/noSelect.js
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap

fixes #379 
Make the weekly tracker look more similar to the wireframe.
**Desktop weekly tracker**
**iPhone X weekly tracker**

Make weekly tracker look more similar to wireframe (#379)

---

client/package.json
client/src/components/Card.jsx

HOTFIX- text selection in education 

---

client/package.json
client/src/components/Chart.jsx

fixes #415 
- Add check for null values and empty strings
- Add all values to the final dataset
yarn test

Fix parsing request from backend logic in Chart component

---

client/package.json
client/src/components/Chart.jsx
client/src/components/Layout.jsx
client/src/components/survey/SurveyPage3.jsx

fixes #404, fixes #417, fixes #419
**#404**: Survey now redirects to home page on successful submission. @JWaltuch 
**#417**: Comments now save properly on survey submission.
**#419**: Certain pages (Home page, about page, etc.) that could not scroll vertically now can.
**#404**: Submit a survey, make sure the home page is automatically naviagated to.
**#417**: Submit a survey, click on the current date on the calendar, make sure …

Survey bug fixes (#404, #417, #419)

---

client/package.json
client/src/components/FactQuizContainer.jsx
client/src/components/Layout.jsx
client/src/components/NavBar.jsx

fixes #421 and also fixes the NavBar on the landscape view on some devices and any problem related to the NavBar position 

fix scroll and navbar on landscape

---

client/package.json
client/src/components/FactQuizContainer.jsx
client/src/components/Layout.jsx
client/src/components/OnboardUser.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/onboarding.js
client/src/redux/reducers/onboarding.js
client/src/redux/reducers/rootReducer.js
client/src/tests/redux/reducers/onboarding.test.js

fixes #409 
- adds onboarding information to Redux store
- persists data in Gaia using a Redux thunk
- adds additional co-morbidities fields to onboarding 
- redirects user on form completion
- **we have another ticket out for changing styling, #408**
- **we can continue to add more co-morbidities fields as we work towards launch**
- Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> …

Add onboarding information to Gaia, Redux

---

client/package.json
client/src/components/survey/SurveyPage1.jsx
client/src/hooks/num-observations.js
client/src/tests/surveys/Survey.test.jsx
client/src/tests/surveys/SurveyPage1.test.jsx
client/src/tests/surveys/SurveyPage2.test.jsx
client/src/tests/surveys/SurveyPage3.test.jsx

Fixes #423
Make emojis larger, add intermittent numbers on sliders, improve desktop styling. Also, have value label above sliders be always visible to be more similar to the wireframe.
**iPhone X survey page 1**
**Desktop survey page 1**

Survey page 1 style updates (#423)

---

client/src/components/toggleinfo.js

Worked on ToggleInfo - Issue 23

---

client/package.json
client/src/components/App.jsx
client/src/components/Calendar.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/FlashCards.jsx
client/src/components/Layout.jsx
client/src/components/Login.jsx
client/src/components/NavBar.jsx
client/src/components/survey/SurveyPage1.jsx
client/src/components/survey/SurveyPage2.jsx
client/src/components/survey/SurveyPage3.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/observations.js
client/src/redux/actions/submit-survey.js

Fixes #400, fixes #403
- Store observations and numObservations on app log in or load
- Fix bug where user is stuck on loading screen when logging out
- Fix a bunch of `propTypes` related errors
- Add new observation to store on survey submission

Improve app log in/log out and initial app load (#400, #403)

---

client/package.json
client/src/components/survey/SurveyPage1.jsx
client/src/components/survey/SurveyPage2.jsx
client/src/components/survey/SurveyPage3.jsx

fixes #444, fixes #445
- Fixes button click bug on survey page 1 where button would not be highlighted after being clicked
- Button clicks on survey page 2 now do not alter their margins
- General survey style improvements for different window sizes
**Note on #444:** I could not reproduce the bug where buttons would not remain highlighted when scrolling on mobile. 
**#444**
**#445**
- Second decimal for major change, third decimal …

Survey buttons (#444, #445)

---

client/src/components/survey/SurveyPage1.jsx

fixes #447
the only change is to text wording no actual code is changed
**Not sure if necessary considering the insignificance of the change**
**Unnecessary**

typo fixed for Survey pg 1 Q3

---

client/package.json
client/src/components/About.jsx
client/src/components/Layout.jsx
client/src/components/More.jsx

Hotfix scroll

---

client/package.json
client/src/components/Chart.jsx
client/src/components/HealthLogToggle.jsx
client/src/components/Layout.jsx
client/src/components/Table.jsx
client/src/components/WeeklyTracker.jsx
client/src/components/WeeklyTrackerDay.jsx
client/src/tests/Chart.test.jsx

Fixes #454
Redux store is now used to get observations to populate the `Chart` and `Table` components. This will speed up the app by reducing fetches.
While viewing network requests made by the app, navigate to the "Show Me More" screen. Notice that no network requests are made.
- [Read here for more …

Use Redux store to get observations (#454)

---

client/package.json
client/src/components/Layout.jsx
client/src/components/survey/Survey.jsx

when navigating between pages/tabs/etc, the window scrolls to the top
fixes #441 
The page scrolls to top when user changes survey page. Couldn't find same issue on any other page.
change pages of the survey.

Always start at top of page

---

client/package.json
client/src/components/toggleinfo.jsx
client/src/utils/fakeCardData.js

fixes #463 
- Adds 10 more "Did you Know?" cards
- Adds 4 more Quiz cards
- Removes any flashcards with relatively blank or incomplete information
It solves the need for our best friends at HackQuarantine to see that things have changed in the UI in the last 8 hours because that is clearly the only measure of progress.
Nothing new added, just more objects added to an array that's only mapped in one location
- Second decimal for …

Update flashcards, added some and removed others

---

client/package.json
client/src/components/More.jsx

fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/469

Fix buttons behavior in More tab

---

client/package.json
client/src/components/Layout.jsx

fixed scrolling behind cards on education screen by adding position fixed to layout and separating navbar and main layout into separate divs
fixes #443
Hi, I made changes to Layout.jsx to fix the scrolling bug in issue #443. I made Layout root div have a fixed position and separated the main root background div and NavBar into separate divs. 
Tested on my Macbook Chrome browser and iPhone 8, All views look good on my end. When I move Education cards, the background stays put. I did not see anything brake on other views.
I was not sure if I need to bump the …

FIX: Layout.jsx - fixed scrolling bug, issue#443

---

client/package.json
client/src/components/Layout.jsx
client/src/components/OnboardUser.jsx

Refactors male & female gender buttons into dropdown list
Fixes mui components from overriding page css
fixes #470 
This fixes issue 470. Removes the Male and Female buttons and uses a muiSelect component instead. An extra gender "non-binary" has been added. 
The muiSelect component was using its own css instead of inheriting from the page (body) css. Therefore, I needed to override those css selectors in Layout.jsx. 
We want to be more gender inclusive, and provide an easy way to extend to more genders in the future. The muiSelect component gives us that ability. …

Refactors male & female gender buttons into dropdown list

---

client/package.json
client/src/components/Card.jsx
client/src/components/FactQuizContainer.jsx
client/src/components/FlashCards.jsx
client/src/components/Layout.jsx

Fix cards postion

---

client/package.json
client/src/components/FlashCards.jsx
client/src/components/HealthLogToggle.jsx
client/src/components/MyHealthLog.jsx
client/src/components/survey/SurveyPage2.jsx

fix buttons in small screens and add Fahrenheit to survey2

---

client/src/components/Calendar.jsx
client/src/components/LogHealthSlider.jsx
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap

Change main view on large screens 

---

client/package.json
client/src/components/ShareButtons.jsx
client/src/tests/ShareButtons.test.jsx
client/yarn.lock

fixes #433 
- Create ShareButtons component with [react-share](https://github.com/nygardk/react-share#readme) library
- Create basic test for ShareButtons component
@BrianHHough We going to need to add template of the message for share and hashtags for some of the social networks. More social networks can be added if needed.
@AdhamAH We need to make a decision where to place this component.
yarn test

ShareButtons component

---

client/package.json
client/src/utils/blockstackHelpers.js

Fix yarn build

---

client/package.json
client/src/components/LogHealthSlider.jsx
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap

fixes #495 
1. Go to Calendar Page in screen sizes
-  screen size >= 839px 
-  screen size < 839px
2. Drag slider just past vertical line
3. See that the slider stays at the line
The slider placement was being calculated based off the screen width and since the slider has a different view width for bigger views I decided to calculate the sliders placement based off the sliders width instead. Now when you go past the vertical line the slider stops at the vertical line.
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / …

get oneThird Value based off slider width instead of screen width

---

client/package.json
client/src/components/Table.jsx
client/src/components/WeeklyTrackerDay.jsx

changed the ratings for "You said you felt?" and "Symptoms" from 10 to 5. Also added "/5" to Overall feeling column in Table component.
fixes #500 

fixed ratings

---

client/package.json
client/public/index.html
client/src/components/Calendar.jsx
client/src/components/Disclaimer.jsx
client/src/components/Layout.jsx
client/src/components/LogHealthSlider.jsx
client/src/components/Login.jsx
client/src/components/NotFoundPage.jsx
client/src/components/OnboardUser.jsx
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap
client/src/utils/imgUrl.js

fixes #472
- Created ```imgUrl.js``` utility file with base url to the images storage and paths to all images. Every path to the external image exported.
- Every image reference to the internal image was replaced to the external location
- Images in ```src/img``` are not deleted.
- yarn start
- serf though the app

Static images to references updated to external storage

---

client/src/components/DeletionDialog.jsx

HOTFIX: Add hosted static files to Deletion Dialog

---

client/package.json
client/src/components/More.jsx
client/src/components/Table.jsx
client/src/components/behavior/chart/BehavioralChart.js

fixes #503 
Adds the ability to unsubscribe a phone number.

Add unsubscribe option (#503)

---

client/package.json
client/src/components/More.jsx
client/src/components/survey/SurveyPage3.jsx

fixes #514 
Adds suggested topics to question 6 in the survey to encourage the user to write about certain topics.

Add suggested topics to Q6 (#514)

---

client/package.json
client/src/components/More.jsx

fixes #518 
Clicking anywhere when modal was popped up closed it. This PR ensures that modal closes on a click outside of modal or on the buttons inside the modal.
Moved Dialog component outside of the Grid component which had the handleClickOpen function on it so since the Dialog was inside the modal was always closing on click since setOpen was being called with (!open) which means false so the modal closed. I also gave all the buttons inside the modal the handleClose func through onClick.
1. Click on more
2. Click anywhere inside modal besides buttons, it wont …

fixed more modal bug

---

README.md
client/package.json

fixes #YOUR-ISSUE-HERE
Hotfix - update of path to the logo image in the README.md
Hotfix - add @babel/compat-data to the pachage.json

Hotfix - add @babel/compat-data and fix path to the logo image in README.md

---

client/package.json
client/src/components/More.jsx

fixes #YOUR-ISSUE-HERE There is no issue 
1- added 8px margin top

HOTFIX- More postion 

---

client/package.json
client/src/components/DeleteAllDataDialog.jsx
client/src/components/OnboardUser.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/deleteUserData.js
client/src/redux/actions/disclaimer.js
client/src/redux/actions/observations.js
client/src/redux/actions/onboarding.js
client/src/redux/reducers/disclaimer.js
client/src/redux/reducers/onboarding.js

fixes #497 
Deleting all `.json` files from gaia and clearing redux store of user data, as opposed to "delete observations" which only deletes survey/observation data in redux/gaia

Delete user data

---

client/package.json
client/src/components/behavior/chart/BehavioralChart.js
client/src/redux/actions/actions.js
client/src/redux/actions/deleteUserData.js

fixes `package.json`
- [] Have you bumped the version in `package.json`? **HOTFIX**
- [] Have you added any new tests necessary?

HOTFIX: Update package.json, fix styling

---

client/package.json
client/public/index.html

Add Fathom analytics

---

client/package.json
client/src/components/Disclaimer.jsx

fixes our likelihood to get sued

HOTFIX: Add links to T&C, Privacy Policy to disclaimer

---

client/package.json
client/src/components/Layout.jsx
client/src/components/Login.jsx
client/src/components/Map.jsx
client/src/components/OnboardUser.jsx
client/src/components/survey/SurveyPage1.jsx
client/src/utils/imgUrl.js

Update logos to beta

---

client/package.json
client/src/components/FlashCards.jsx

fixes #551 
Fixes quiz score bug where right swipe would be considered `false` and left `true`.

Fix quiz score bug (#551)

---

client/package.json
client/src/components/About.jsx
client/src/components/Layout.jsx
client/src/components/LogHealthSlider.jsx
client/src/components/Login.jsx
client/src/components/OnboardUser.jsx
client/src/components/Table.jsx
client/src/components/survey/SurveyPage1.jsx
client/src/components/survey/SurveyPage2.jsx
client/src/components/survey/SurveyPage4.jsx
client/src/tests/__snapshots__/LogHealthSlider.test.jsx.snap

fixes #558 
**These are temporary measures to make the app usable for launch. We can continue to update/edit to make our styling cleaner overall as we develop**

Fix up mobile styling

---

client/src/components/Login.jsx

HOTFIX: inform users to disable popups on mobile

---

client/package.json
client/src/components/App.jsx
client/src/components/More.jsx
client/src/components/OnboardUser.jsx
client/src/components/Settings.jsx

fixes #587 
Creating a page dedicated to settings instead of it being the onboard page.
1. Click on more
2. Click on settings 
3. Takes you to settings page
4. Click on Update Information Button to go to onboard page to change info.

created settings page

---

client/package.json
client/src/components/OnboardUser.jsx

fixes #589 
Was hard to tell if a field was a dropdown or a text input. Changed styling for inputs to be different from UI buttons. Made Placeholder for text input to say "Enter Age" etc. Made Age input a number input. 
Go to Onboard page to see view.
1. Click More
2. Click Update Information
- [Read here for …

fixed onboard textinputs

---

client/package.json
client/src/components/About.jsx
client/src/utils/imgUrl.js

Add additional accomplishments to about page

---

client/package.json
client/src/components/App.jsx

Set zoom to 100% always

---

client/package.json
client/src/components/FlashCards.jsx
client/src/utils/fakeCardData.js

fixes #577 
Changed data={cardData[cardData.length - i - 1]} to data={cardData[i]} in FlashCards component
Also fixed fact numbers in fakeCardData.js
Flashcards would show up in reverse order starting with fact 15 and going to fact 1
fakeCardData went 1,2,6,7,8,8 ... just fixed the numbering
- [Read here for …

Reversed map ordering of flashcards to reflect numbering

---

client/package.json
client/src/components/About.jsx

fixes #616 
Make the About Cards Interactive

added links

---

client/package.json
client/public/locales/nl/translation.json
client/src/utils/constants.js

fixes #595
- Create directory for Dutch language `client/public/locales/nl` with `translation.json` in it with Dutch language content. 
- Add Dutch language to the constant.js
yarn start
click on language select menu and pick Dutch

Adding Dutch language to the app

---

client/package.json
client/src/components/More.jsx
client/src/components/Table.jsx

-----
Fixes #630 
Checks phone numbers client-side to ensure they comply with E.164 which is necessary for Twilio.
- Checking on the frontend because this is a quick check to do and isn't worth a backend requests
- Updated success message to display a success snackbar similar …

Check for valid phone numbers before subscribing

---

client/package.json
client/src/components/Settings.jsx

-----
Fixes #634 
- Adds language selector to settings page
- Automatically updates language when navigating to other pages
Not much to test here besides checking out the code and seeing
- Update the third decimal for a minor …

Add language selector to settings

---

client/package.json
client/src/components/Settings.jsx

-----
Fixes #636 
Added Links to Terms & Conditions/Privacy Policy pages in Settings component at the very bottom.
Here is a gif showing it:
- Numbers can go past 9, e.g. `1.0.9` => …

Links to Terms and Conditions/Privacy Policy pages in Settings.jsx

---

Translations/appText.json

This reverts commit ef91e839974e3268bf0af6348fbcd800903a4409.
-----
Fixes commit that was merged directly into master
Commit was made directly to master and every commit has to follow our PR process as outlined across our documentation, contributing guidelines, etc

HOTFIX: Revert "Updated JSON File (as of 4/26/20)"

---

client/package.json
client/src/components/WeeklyTracker.jsx
client/src/components/survey/SurveyPage1.jsx

-----
Fixes #640
After swiping on weeklyTrackerDay it takes you to showMeMore of the single observation.
In a previous PR I had fixed how the toggle Value was set so now toggleValue 'showMeMore' should take you to your observations instead of 'myHealthLog'.
I also noticed that …

Weekly slider bug fix

---

client/package.json
client/src/components/NavBar.jsx

-----
Fixes #615 
changed the colour of `NavBar.jsx`
- Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
- For more info, read about [Semantic Versioning](https://semver.org/)

change navbar colour

---

client/package.json
client/src/components/About.jsx

-----
Fixes #646 
Replaces beta survey link in About.jsx
New link takes users to a survey they can fill out. 
- Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
- For more info, read …

update beta survey link in About.jsx 

---

client/package.json
client/src/components/Layout.jsx
client/src/components/OnboardUser.jsx
client/src/redux/reducers/onboarding.js
client/src/redux/reducers/rootReducer.js
client/src/tests/redux/reducers/onboarding.test.js
client/src/utils/constants.js

-----
Fixes #582 
* Form style changes
* Use more material components
* Make state input a dropdown
**iPhone X**
**Desktop**
**State dropdown**
- Numbers can go past 9, e.g. `1.0.9` => …

Onboard improvements (#582)

---

client/package.json
client/src/components/Calendar.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/Translations.jsx

-----
Fixes #663 
* Greeting date uses selected language
* Calendar uses selected language
* Fix bug where going to settings page would reset language to English
- Numbers can go past …

Use selected language for greeting date and calendar (#663)

---

client/package.json
client/src/components/WeeklyTrackerDay.jsx

-----
Fixes #658 
Adds an indicator for the user to swipe WeeklyTracker.jsx 
- [X ] For CoronaTracker, did you bump the version in `package.json`?
- Numbers can go past 9, e.g. `1.0.9` …

add indicator to swipe WeeklyTracker.jsx

---

client/package.json
client/src/components/App.jsx
client/src/components/DeleteAllDataDialog.jsx
client/src/components/DeletionDialog.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/More.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/survey.js
client/src/redux/reducers/survey.js
client/src/tests/redux/reducers/survey.test.js

-----
Fixes #668 
Gives a user a reminder every time they log in to take their survey if they haven't taken one that day.
If a user deletes their data they'll be reminded to take a survey upon going back to the health Log.
Before a user was forced to take a survey if they …

Survey reminder

---

client/package.json
client/src/components/OnboardUser.jsx

-----
Fixes #686 
1- changed the `variant` of  the questions from `subtitle2` to `body1`
2- changed the grid of the questions to `5` inside of `6`
- Numbers can go past 9, e.g. `1.0.9` …

Onboard small screens fix

---

README.md
ROADMAP-TO-MVP.md
Translations/README.md
design/README.md

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.
-----
Fixes #674 and #675 
This PR adds the relevant information for the ROADMAP-TO-MVP document to the main repo readme, and includes some other minor documentation updates.
See commit history.
Reviewed all changes in Markdown preview for errors.
- **n/a** For CoronaTracker, …

Update Corona-tracker docs for ROADMAP-TO-MVP

---

.travis.yml

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.
Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md
-----
Fixes #692
This pull request updates the formatting of the travis.yml file to ensure each command is run individually.
I am not a Travis CI pro so a thorough review is appreciated, but from the way I understand it, the changes to this file should fix the build process. …

Update travis.yml to run separate commands

---

client/package.json
client/src/components/showMeMore/Download.jsx
client/src/components/showMeMore/ShowMeContainer.jsx
client/src/utils/constants.js
client/yarn.lock

-----
Fixes #632 
- Downloads observations as an Excel file on button on "Show Me More"
**Currently still co-authoring with @rachelafrick**
- Numbers can go past 9, e.g. `1.0.9` => …

Add export to Excel functionality

---

client/package.json
client/src/components/FlashCards.jsx
client/src/components/QuizScoreDialog.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/education.js
client/src/redux/reducers/education.js
client/src/redux/reducers/rootReducer.js

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.
Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md
-----
Fixes #700
Add score dialog for quiz view.
- Create `QuizScoreDialog` component
- Add conditional rendering to the `FlashCards` component
- yarn start
- login
- hit rout `/education`
- select `quiz`
- swipe all cards
- …

Add score dialog
