COVID-19-electronic-health-system/Corona-tracker

client/src/css/NavBar.css

* Addresses #38 
* NavBar is now sticky to the bottom and responsive to small images.
* NavBar Items are now evenly spaced.
* __Note:__
* Did not include extra spacing under the icons, shown in [here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/CORONATRACKER%20UI%20-%20Login%20Screen.png)
* Also, icons cover the whole span instead of being slightly more padded inward

Fixed NavBar that was stuck to the top

---

README.md
client/.gitignore
client/src/components/App.js
client/src/models/patient.js

[Ticket](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/48)
I've managed to set up a (hopefully) working very simple QA database that we can all access and interact with the same data. 
This little mockup will do a better job explaining than I can. Now, instead of having to run both MongoDB and a Radiks server locally, we can all connect to the same Radiks server running on an AWS EC2 instance and persisting data we add / manipulate to the same database running on a MongoDB cluster.
For security purposes, as the EC2 instance is already a little insecure in terms of inbound traffic, and just for good practice, I've implemented a `REACT_APP_QA_URL` environment variable for the public DNS of the EC2. You can just ask me for it, or I'll figure out the best way to …

Setup codebase to access QA environment

---

CONTRIBUTING.md

Quick update for `CONTRIBUTING.md` as per request by @tesla809 .
Also, changed times where the doc says `this tool` to the actual tool's name for clarity. Sorry, I did not follow the template for this PR :x

Added gyazo as a part of the suggested software for .gifs and updated the link for byzanz in CONTRIBUTING.md

---

client/package.json
client/src/components/App.js
client/src/components/Login.js

This PR
* replaces `blockstack.redirectToSignIn` with `connect.doOpenAuth`
* closes #93 
The connect library was developed by Blockstack's user experience team to improve the on-boarding of new users. 
**Test plan (required)**
1. start radiks or set QA_URL
1. Checkout this branch
1. `yarn`
1. `yarn start`
1. Visit 127.0.0.1:3000
1. if logged-in logout
1. click `Get started` and follow the out flow
1. click sign out
Sign In Flow
Sign out Flow

Use @blockstack/connect for improved UX

---

CONTRIBUTING.md
client/.env.production
client/.gitignore

Closes #155 
- Added a new Radiks cluster running on an EC2 instance, linked to a new MongoDB Atlas Cluster. This satisfies the condition @friedger actually specified a few months back to someone else who had a [similar question](https://github.com/blockstack/radiks/issues/40)! 
- Updated the `README` - we now have two environments, so we have two different environment variable files: `.env.development` and `.env.production`. For most cases, we'll be setting `.env.development` to access the QA environment. You should only be setting `.env.production` if you're looking to make prod changes, which should be thoroughly vetted.

Setup demo prod deployment

---

client/.gitignore

- Added `.env.production` to our gitignore so that nobody can see our "demo prod" endpoint

Add development environment variable to gitignore

---

client/src/components/App.js
client/src/components/PrivateRoute.js

**Description of change** => replaces protected routes with PrivateRoute component, which receives as props the authed state, the path, and the component to render, and conditionally renders either the component received as a prop or the Login component.
**Alternate designs** => either keep authed state in redux so that we can connect the PrivateRoute component to the store and not need to pass authed on every route, or... I've been given the impression that there is a way that we can access the userSession data from Radiks in any component, so that could provide a similar solution. I have no experience in Radiks and haven't been able to figure out how to do that.
**Possible drawbacks** => need to pass authed boolean to every route, may eventually affect readability.

#164 PrivateRoute component

---

client/src/components/App.js
client/src/components/Disclaimer.js

Changed attribute in PrivateRoute (render => component). You can now navigate to the education page. Also added state to the Disclaimer.js so when uncommented, the disclaimer will disappear after agreeing. 
fixes #196

Fixed routing to Education 

---

client/src/components/Subscribe.js

fixes #248 
This wires up the frontend button to request subscription to our notifications service to the backend API which subscribes the user. 
**NOTE:** I am hardcoding in the URL, but I believe this is fine as the request is being sent over HTTPS, not HTTP.
Right now, this backend service is very rudimentary. Unsubscribe functionality is currently not fully working, so for now, we're just subscribing a user for one day, at which point the server will reset and all data will be lost (thus unsubscribing the user). This is incredibly hacky, but between making sure everything else is running smoothly and trying to push this out in 2 days, it's the best I could do :)
Currently, the service is deployed on my private AWS account. Going forward, I will look to create at least a free-tier AWS …

Subscribe to notifications service alpha via API Gateway

---

client/public/index.html
client/src/components/App.js
client/src/components/MyHealthLog.js

No issue as these are necessary fixes that needed to be completed on the spot for the build to deploy to S3.

HOTFIX: Changes necessary to deploy React build

---

client/src/components/SymptomsTracker.js
client/src/components/survey-view/checkbox-button/CheckboxButton.js
client/yarn.lock

fixes #255 
- Button click callback in `SymptomsTracker` now has a reference to the child component, `CheckboxButton`, allowing state to be saved in Redux and persisted to database all at once.
**Is `useRef` the best way to go about this? Aside from a somewhat extensive re-architecting of how we have these components laid out?**

Reference child component to pre for Redux

---

CONTRIBUTING.md

fixed typo in path to adding upstream git. Fixed it without space between path and Corona-tracker. git@github.com:COVID-19-electronic-health-system/Corona-tracker.git
Without it, the instructions to set up upstream for pulling main repo will not work.

HOTFIX: Update CONTRIBUTING.md

---

client/src/components/SymptomsTracker.js

fixes #292 
- as title states, we're not using `window.location.reload()` anymore, as that breaks the authentication and will not work in production

Used useHistory to redirect to health log on survey submission

---

client/src/components/App.js

We need to remove the alert every 5 seconds as it's interfering too much with the UX. Can re-implement later.

HOTFIX: Remove alert

---

client/package.json
client/src/components/survey-view/checkbox-button/SingleCheckboxButton.jsx

Simply checks the symptom checkbox to determine whether the severity buttons should be disabled or not.
fixes #318

#318 disable severity buttons unless the symptom is checked

---

client/package.json
client/src/components/Calendar.jsx
client/src/components/DiagnosticContainer.jsx
client/src/components/MyHealthLog.jsx
client/src/components/WeeklyTracker.jsx
client/src/components/WeeklyTrackerDay.jsx
client/src/tests/Calendar.test.jsx

fixes #338 
Added functionality so that when the user clikcs on a calendar date, the associated WeeklyTracker components will display below the calendar. Definitely need styling (I will make another issue), but it works.
Added a basic Calendar-rendering test - **as I've said in other PRs - will write out individual stories to backfill tests. I know it's not good practice, but we have 12 days until beta**.
- Second decimal for major …

Show WeeklyTrackers on date click

---

client/package.json
client/yarn.lock

fixes #405 
Ran yarn remove react-with-gesture
To remove deprecated dependancy on react-with-gesture for focus on react-use-gesture
Sorry I didn't think to take a screenshot of the command output before running yarn run start to test. The output had some warnings but no errors. The fact that there are no changes in the package.json and yarn.lock files supports this. I also tested the drag gesture and it works both on my phone and on desktop. 
https://gyazo.com/e6279b18c09c3a2ac59753858f4c4983
- [Read here for more …

Removed react-with-gesture

---

client/package.json
client/src/components/App.jsx
client/src/components/OnboardUser.jsx
client/src/redux/actions/actions.js
client/src/redux/actions/onboarding.js
client/src/redux/reducers/onboarding.js
client/src/tests/redux/reducers/onboarding.test.js

fixes #541 
Previously saved user data should be displayed as the default values on the user onboard form, rather than a blank form.
Initial form state was previously hardcoded in onboard component.  Initial formstate in component is now the user's onboard data state mapped from redux store.  Initial state in the store updated to reflect the shape of a blank form.  Redux action changed to reflect fetching vs setting the user's onboard data.  Fetch action added to useEffect in App.jsx.
- Second decimal for major change, third decimal for minor change. This can go past …

Onboard form displays previous saved user data

---

client/package.json
client/src/components/survey/SurveyPage2.jsx

fixes #586 
Buttons would deselect in mobile browser. After inspecting it on mobile I found that the innerText obtained from clicking was different depending on where you clicked. If you log the e.target you'll see that clicking on the edge targets the button element but clicking in the middle targets the span element. So I inspected further and saw that the value for innerText were different, for the button it had a value of Minimal but with a new line vs the span where it has Minimal as we wanted. So when we do the ternary for determining a selected button it would …

Survey2 buttons

---

client/package.json
client/src/components/Table.jsx

Fixes #619
- user can select charts with many records in the table
- Move charts checkboxes above table with survey results
- Move charts above table with survey results
- Adjust style of the charts container to fix gap between chart and table containers
- Add dynamic rendering of the charts and table of the survey results
- yarn start
- click `show me more`
- select `Fever` or `Behavioral` 
I think that `show me more` view is overloaded with 2 charts and survey results table. I would suggest conditional rendering based on user selection. If user select fever chart, we can hide table to make view let over loaded with content. Open for dialog!  
- Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
- …

Refactor of the Table component

---

client/package.json
client/src/components/showMeMore/Observations.jsx

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.
Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md
-----
Fixes #697 
When there is only one observation, the observation details will automatically open.
- [ x] For CoronaTracker, did you bump the version in `package.json`?
- Numbers …

automatically open observation detail when there is only one observation
